### ISSUE TITLE
Search result text display

### ISSUE THREAD

**Issue by kara-krzystan** [benmcrae5/uofa-bootcamp-project-1#38]
Need to display text results of users search. 
Results are returned as an array, display will be comma separated 
(ex. Mars, Venus, Neptune)

To match code already in Javascript, use id= visibleList

Would probably look best on top of pretty image

**Comment by kristinmoon** [comment]
Do we still want this even though the planet names are listed above each individual image?

**Comment by benmcrae5** [comment]
I would vote that the display with the planet names/pictures should be plenty for our output, as long as it's in a concise and readable layout. =)

**Comment by kristinmoon** [comment]
Agreed! Closing now.
