### ISSUE TITLE
create slides for presentation?

### ISSUE THREAD

**Issue by kristinmoon** [benmcrae5/uofa-bootcamp-project-1#48]
There was talk of this in class today... do we need a powerpoint or keynote presentation? We should discuss our presentation.

**Comment by kara-krzystan** [comment]
Looks like Module 8 provides the full outline of the project requirements as well as grading criteria.
There is also a presentation template for us to use, it's google slides.

**Comment by kristinmoon** [comment]
Thanks again to @kara-krzystan!
