### ISSUE TITLE
Get NASA Image and Video Library API key

### ISSUE THREAD

**Issue by kristinmoon** [benmcrae5/uofa-bootcamp-project-1#5]
https://api.nasa.gov/
https://images.nasa.gov/

Use this API to access the NASA Image and Video Library site at images.nasa.gov. For the latest documentation, please go here: https://images.nasa.gov/docs/images.nasa.gov_api_docs.pdf

The images.nasa.gov API is organized around REST, has predictable/resource­-oriented URLs and uses HTTP response codes to indicate API errors. This API uses built-­in HTTP features such as HTTP authentication and HTTP verbs, which are understood by many off-­the-­shelf HTTP clients. Please note that JSON is returned by all API responses, including errors. Each of the endpoints described below also contains example snippets which use the curl command­-line tool, Unix pipelines, and the python command­-line tool to output API responses in an easy­ to ­read format.

**Comment by kara-krzystan** [comment]
Registered and now have a key that works across all NASA APIs. Will add to our JS file, then close this issue
